program: train.py
method: bayes
name: sweep
metric:
  name: val_pearson
  goal: maximize
parameters:
  batch_size:
    values: [4,8,16,32]
  epochs:
    distribution: int_uniform
    min: 2
    max: 6
  learning_rate:
    distribution: 'uniform'
    min: 1e-5
    max: 0.01
  optimizer:
    values: ["adam","adamW"]
early_terminate:
    type: 'hyperband'
    min_iter: 4

