model_name: 'klue/roberta-base'

parameter: 
  batch_size: 32
  max_epoch: 16
  shuffle: True
  learning_rate: 1e-5

path:
  train: './data/train.csv'
  dev: './data/dev.csv'
  test: './data/dev.csv'
  predict: './data/test.csv'

sweep: 
  isSweep: True
  sweepCnt: 10